# Script to automatically identify WDF function pointers
# Inspired by http://redplait.blogspot.ru/2012/12/wdffunctionsidc.html
# Originally by Nicolas Guigo, modified by Braden Hollembaek and Adam Pond

from idautils import *
from idaapi import *
from idc import *
import ida_search

# Architecture dependent globals
archinfo = get_inf_structure()
if archinfo.is_64bit():
    FF_PTR = FF_QWORD
    get_ptr = get_64bit
    ptr_size = 8
else:
    FF_PTR = FF_DWORD
    get_ptr = get_32bit
    ptr_size = 4

def log(string):
    print('[+]: ' + string)

def add_struct(version):
    id = BADADDR
    offset = 0
    # check for existing
    id = get_struc_id('WDFFUNCTIONS')
    if id != BADADDR:
        # delete old struc
        del_struc(id)
    log('Creating struct for WDF Functions version 1.%d' % version)
    id = add_struc(BADADDR, 'WDFFUNCTIONS', 0)
    if id != BADADDR:
        add_struc_member(id, "pfnWdfChildListCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListRetrievePdo", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListRetrieveAddressDescription", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListBeginScan", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListEndScan", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListBeginIteration", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListRetrieveNextDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListEndIteration", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListAddOrUpdateChildDescriptionAsPresent", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListUpdateChildDescriptionAsMissing", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListUpdateAllChildDescriptionsAsPresent", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfChildListRequestChildEject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionGetCount", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionAdd", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionRemove", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionRemoveItem", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionGetItem", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionGetFirstItem", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCollectionGetLastItem", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCommonBufferCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCommonBufferGetAlignedVirtualAddress", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCommonBufferGetAlignedLogicalAddress", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCommonBufferGetLength", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfControlDeviceInitAllocate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfControlDeviceInitSetShutdownNotification", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfControlFinishInitializing", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetDeviceState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetDeviceState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWdmDeviceGetWdfDeviceHandle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceWdmGetDeviceObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceWdmGetAttachedDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceWdmGetPhysicalDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceWdmDispatchPreprocessedIrp", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceAddDependentUsageDeviceObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceAddRemovalRelationsPhysicalDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceRemoveRemovalRelationsPhysicalDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceClearRemovalRelationsDevices", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetDriver", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceRetrieveDeviceName", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceAssignMofResourceName", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetIoTarget", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetDevicePnpState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetDevicePowerState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetDevicePowerPolicyState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceAssignS0IdleSettings", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceAssignSxWakeSettings", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceOpenRegistryKey", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetSpecialFileSupport", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetCharacteristics", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetCharacteristics", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetAlignmentRequirement", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetAlignmentRequirement", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitFree", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetPnpPowerEventCallbacks", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetPowerPolicyEventCallbacks", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetPowerPolicyOwnership", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitRegisterPnpStateChangeCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitRegisterPowerStateChangeCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitRegisterPowerPolicyStateChangeCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetIoType", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetExclusive", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetPowerNotPageable", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetPowerPageable", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetPowerInrush", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetDeviceType", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitAssignName", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitAssignSDDLString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetDeviceClass", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetCharacteristics", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetFileObjectConfig", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetRequestAttributes", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitAssignWdmIrpPreprocessCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceInitSetIoInCallerContextCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetStaticStopRemove", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceCreateDeviceInterface", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetDeviceInterfaceState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceRetrieveDeviceInterfaceString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceCreateSymbolicLink", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceQueryProperty", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceAllocAndQueryProperty", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetPnpCapabilities", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetPowerCapabilities", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetBusInformationForChildren", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceIndicateWakeStatus", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceSetFailed", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceStopIdle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceResumeIdle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetFileObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceEnqueueRequest", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceGetDefaultQueue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceConfigureRequestDispatching", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaEnablerCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaEnablerGetMaximumLength", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaEnablerGetMaximumScatterGatherElements", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaEnablerSetMaximumScatterGatherElements", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionInitialize", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionInitializeUsingRequest", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionExecute", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionRelease", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionDmaCompleted", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionDmaCompletedWithLength", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionDmaCompletedFinal", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionGetBytesTransferred", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionSetMaximumLength", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionGetRequest", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionGetCurrentDmaTransferLength", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaTransactionGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDpcCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDpcEnqueue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDpcCancel", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDpcGetParentObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDpcWdmGetDpc", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverGetRegistryPath", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverWdmGetDriverObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverOpenParametersRegistryKey", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWdmDriverGetWdfDriverHandle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverRegisterTraceInfo", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverRetrieveVersionString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverIsVersionAvailable", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoInitWdmGetPhysicalDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoInitOpenRegistryKey", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoInitQueryProperty", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoInitAllocAndQueryProperty", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoInitSetEventCallbacks", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoInitSetFilter", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoInitSetDefaultChildListConfig", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoQueryForInterface", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoGetDefaultChildList", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoAddStaticChild", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoLockStaticChildListForIteration", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoRetrieveNextStaticChild", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFdoUnlockStaticChildListFromIteration", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFileObjectGetFileName", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFileObjectGetFlags", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFileObjectGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfFileObjectWdmGetFileObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptQueueDpcForIsr", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptSynchronize", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptAcquireLock", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptReleaseLock", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptEnable", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptDisable", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptWdmGetInterrupt", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptGetInfo", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptSetPolicy", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfInterruptGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueGetState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueStart", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueStop", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueStopSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueRetrieveNextRequest", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueRetrieveRequestByFileObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueFindRequest", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueRetrieveFoundRequest", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueDrainSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueDrain", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueuePurgeSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueuePurge", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoQueueReadyNotify", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetOpen", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetCloseForQueryRemove", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetClose", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetStart", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetStop", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetGetState", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetQueryTargetProperty", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetAllocAndQueryTargetProperty", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetQueryForInterface", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetWdmGetTargetDeviceObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetWdmGetTargetPhysicalDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetWdmGetTargetFileObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetWdmGetTargetFileHandle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetSendReadSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetFormatRequestForRead", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetSendWriteSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetFormatRequestForWrite", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetSendIoctlSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetFormatRequestForIoctl", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetSendInternalIoctlSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetFormatRequestForInternalIoctl", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetSendInternalIoctlOthersSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoTargetFormatRequestForInternalIoctlOthers", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfMemoryCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfMemoryCreatePreallocated", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfMemoryGetBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfMemoryAssignBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfMemoryCopyToBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfMemoryCopyFromBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfLookasideListCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfMemoryCreateFromLookaside", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceMiniportCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDriverMiniportUnload", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectGetTypedContextWorker", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectAllocateContext", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectContextGetObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectReferenceActual", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectDereferenceActual", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectDelete", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectQuery", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitAllocate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitSetEventCallbacks", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitAssignDeviceID", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitAssignInstanceID", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitAddHardwareID", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitAddCompatibleID", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitAddDeviceText", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitSetDefaultLocale", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoInitAssignRawDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoMarkMissing", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoRequestEject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoGetParent", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoRetrieveIdentificationDescription", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoRetrieveAddressDescription", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoUpdateAddressDescription", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoAddEjectionRelationsPhysicalDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoRemoveEjectionRelationsPhysicalDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfPdoClearEjectionRelationsDevices", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDeviceAddQueryInterface", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryOpenKey", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryCreateKey", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryClose", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryWdmGetHandle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryRemoveKey", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryRemoveValue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryQueryValue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryQueryMemory", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryQueryMultiString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryQueryUnicodeString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryQueryString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryQueryULong", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryAssignValue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryAssignMemory", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryAssignMultiString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryAssignUnicodeString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryAssignString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRegistryAssignULong", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestCreateFromIrp", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestReuse", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestChangeTarget", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestFormatRequestUsingCurrentType", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestWdmFormatUsingStackLocation", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestSend", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestGetStatus", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestMarkCancelable", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestUnmarkCancelable", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestIsCanceled", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestCancelSentRequest", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestIsFrom32BitProcess", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestSetCompletionRoutine", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestGetCompletionParams", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestAllocateTimer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestComplete", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestCompleteWithPriorityBoost", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestCompleteWithInformation", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestGetParameters", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveInputMemory", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveOutputMemory", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveInputBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveOutputBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveInputWdmMdl", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveOutputWdmMdl", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveUnsafeUserInputBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRetrieveUnsafeUserOutputBuffer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestSetInformation", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestGetInformation", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestGetFileObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestProbeAndLockUserBufferForRead", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestProbeAndLockUserBufferForWrite", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestGetRequestorMode", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestForwardToIoQueue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestGetIoQueue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestRequeue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestStopAcknowledge", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfRequestWdmGetIrp", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListSetSlotNumber", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListSetInterfaceType", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListAppendIoResList", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListInsertIoResList", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListGetCount", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListGetIoResList", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListRemove", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceRequirementsListRemoveByIoResList", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListAppendDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListInsertDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListUpdateDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListGetCount", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListGetDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListRemove", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfIoResourceListRemoveByDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCmResourceListAppendDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCmResourceListInsertDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCmResourceListGetCount", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCmResourceListGetDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCmResourceListRemove", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCmResourceListRemoveByDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfStringCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfStringGetUnicodeString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectAcquireLock", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfObjectReleaseLock", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWaitLockCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWaitLockAcquire", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWaitLockRelease", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfSpinLockCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfSpinLockAcquire", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfSpinLockRelease", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfTimerCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfTimerStart", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfTimerStop", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfTimerGetParentObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceRetrieveInformation", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceGetDeviceDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceRetrieveConfigDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceQueryString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceAllocAndQueryString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceFormatRequestForString", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceGetNumInterfaces", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceSelectConfig", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceWdmGetConfigurationHandle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceRetrieveCurrentFrameNumber", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceSendControlTransferSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceFormatRequestForControlTransfer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceIsConnectedSynchronous", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceResetPortSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceCyclePortSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceFormatRequestForCyclePort", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceSendUrbSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceFormatRequestForUrb", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeGetInformation", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeIsInEndpoint", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeIsOutEndpoint", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeGetType", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeSetNoMaximumPacketSizeCheck", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeWriteSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeFormatRequestForWrite", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeReadSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeFormatRequestForRead", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeConfigContinuousReader", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeAbortSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeFormatRequestForAbort", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeResetSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeFormatRequestForReset", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeSendUrbSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeFormatRequestForUrb", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetInterfaceNumber", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetNumEndpoints", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetDescriptor", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceSelectSetting", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetEndpointInformation", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetDeviceGetInterface", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetConfiguredSettingIndex", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetNumConfiguredPipes", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetConfiguredPipe", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbTargetPipeWdmGetPipeHandle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfVerifierDbgBreakPoint", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfVerifierKeBugCheck", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiProviderCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiProviderGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiProviderIsEnabled", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiProviderGetTracingHandle", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiInstanceCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiInstanceRegister", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiInstanceDeregister", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiInstanceGetDevice", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiInstanceGetProvider", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWmiInstanceFireEvent", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWorkItemCreate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWorkItemEnqueue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWorkItemGetParentObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfWorkItemFlush", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfCommonBufferCreateWithConfig", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaEnablerGetFragmentLength", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfDmaEnablerWdmGetDmaAdapter", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        add_struc_member(id, "pfnWdfUsbInterfaceGetNumSettings", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
        if version >= 5:
            add_struc_member(id, "pfnWdfDeviceRemoveDependentUsageDeviceObject", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfDeviceGetSystemPowerAction", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfInterruptSetExtendedPolicy", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfIoQueueAssignForwardProgressPolicy", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfPdoInitAssignContainerID", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfPdoInitAllowForwardingRequestToParent", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfRequestMarkCancelableEx", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfRequestIsReserved", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            add_struc_member(id, "pfnWdfRequestForwardToParentDeviceIoQueue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
            if version >= 9:
                add_struc_member(id, "pfnWdfCxDeviceInitAllocate", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfCxDeviceInitAssignWdmIrpPreprocessCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfCxDeviceInitSetIoInCallerContextCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfCxDeviceInitSetRequestAttributes", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfCxDeviceInitSetFileObjectConfig", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDeviceWdmDispatchIrp", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDeviceWdmDispatchIrpToIoQueue", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDeviceInitSetRemoveLockOptions", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDeviceConfigureWdmIrpDispatchCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaEnablerConfigureSystemProfile", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionInitializeUsingOffset", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionGetTransferInfo", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionSetChannelConfigurationCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionSetTransferCompleteCallback", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionSetImmediateExecution", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionAllocateResources", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionSetDeviceAddressOffset", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionFreeResources", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionCancel", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionWdmGetTransferContext", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfInterruptQueueWorkItemForIsr", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfInterruptTryToAcquireLock", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfIoQueueStopAndPurge", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfIoQueueStopAndPurgeSynchronously", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfIoTargetPurge", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfUsbTargetDeviceCreateWithParameters", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfUsbTargetDeviceQueryUsbCapability", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfUsbTargetDeviceCreateUrb", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfUsbTargetDeviceCreateIsochUrb", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDeviceWdmAssignPowerFrameworkSettings", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDmaTransactionStopSystemTransfer", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfCxVerifierKeBugCheck", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfInterruptReportActive", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfInterruptReportInactive", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfDeviceInitSetReleaseHardwareOrderOnFailure", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                add_struc_member(id, "pfnWdfGetTriageInfo", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                if version >= 11:
                     add_struc_member(id,"pfnWdfDeviceInitSetIoTypeEx", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                     add_struc_member(id,"pfnWdfDeviceQueryPropertyEx", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                     add_struc_member(id,"pfnWdfDeviceAllocAndQueryPropertyEx", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                     add_struc_member(id,"pfnWdfDeviceAssignProperty", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                     add_struc_member(id,"pfnWdfFdoInitQueryPropertyEx", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                     add_struc_member(id,"pfnWdfFdoInitAllocAndQueryPropertyEx", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                     if version >= 13:
                         add_struc_member(id,"pfnWdfDeviceStopIdleActual", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
                         add_struc_member(id,"pfnWdfDeviceResumeIdleActual", BADADDR, FF_DATA|FF_PTR, 0, ptr_size)
    return id

def populate_wdf():
    # find data sections
    segment_starts = [get_segm_by_name('.data').start_ea, get_segm_by_name('.rdata').start_ea]
    for ea in segment_starts:
        if ea != BADADDR:
            # find "KmdfLibrary" unicode string in .rdata section
            idx = ida_search.find_binary(ea, BADADDR, " ".join("{0:02x}".format(c) for c in "KmdfLibrary".encode('utf-16le')).upper(), 16, SEARCH_DOWN)
            if idx != BADADDR:
                log('Found "KmdfLibrary" unicode string at ' + hex(idx))
                addr = get_first_dref_to(idx)
                # hacky logic fix , consider only the minor portion
                version = int(str(get_wide_dword(addr+ptr_size+0x4)))
                id = add_struct(version)
                if id != BADADDR:
                    log('Success')
                    wdf_func = get_ptr(addr+ptr_size+0x14)
                    size = get_struc_size(id)
                    log('create_struct (size=' + hex(size) + ') at ' +  hex(wdf_func))
                    del_items(wdf_func, 0, size)
                    if create_struct(wdf_func, -1, get_struc_name(id)) and set_name(wdf_func, 'WdfFunctions', 0):
                        log('Success')
                    else:
                        log('Failure')
